/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>
#include "fault_injection_messages.h"

#if !defined(_MSC_VER) || _MSC_VER >= 1800
void MemoryInjectionAction_maskOperation_Initialize(MemoryInjectionAction_maskOperation* pVal)
{
    *pVal = (MemoryInjectionAction_maskOperation) 0;
}
#endif

 
flag MemoryInjectionAction_maskOperation_IsConstraintValid(const MemoryInjectionAction_maskOperation* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (*pVal <= 2);
	*pErrCode = ret ? 0 : ERR_MemoryInjectionAction_maskOperation;

	return ret;
}

flag MemoryInjectionAction_maskOperation_Encode(const MemoryInjectionAction_maskOperation* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? MemoryInjectionAction_maskOperation_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, *pVal, 0, 2);
    }

	return ret;
}

flag MemoryInjectionAction_maskOperation_Decode(MemoryInjectionAction_maskOperation* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 2);
	*pErrCode = ret ? 0 : 268435457;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void MemoryInjectionAction_omitCallsNumber_Initialize(MemoryInjectionAction_omitCallsNumber* pVal)
{
    *pVal = (MemoryInjectionAction_omitCallsNumber) 0;
}
#endif

 
flag MemoryInjectionAction_omitCallsNumber_IsConstraintValid(const MemoryInjectionAction_omitCallsNumber* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (*pVal <= 4294967295LL);
	*pErrCode = ret ? 0 : ERR_MemoryInjectionAction_omitCallsNumber;

	return ret;
}

flag MemoryInjectionAction_omitCallsNumber_Encode(const MemoryInjectionAction_omitCallsNumber* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? MemoryInjectionAction_omitCallsNumber_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, *pVal, 0, 4294967295LL);
    }

	return ret;
}

flag MemoryInjectionAction_omitCallsNumber_Decode(MemoryInjectionAction_omitCallsNumber* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 4294967295LL);
	*pErrCode = ret ? 0 : 268435458;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void MemoryInjectionAction_valueMask_Initialize(MemoryInjectionAction_valueMask* pVal)
{
    *pVal = (MemoryInjectionAction_valueMask) 0;
}
#endif

 
flag MemoryInjectionAction_valueMask_IsConstraintValid(const MemoryInjectionAction_valueMask* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (*pVal <= 4294967295LL);
	*pErrCode = ret ? 0 : ERR_MemoryInjectionAction_valueMask;

	return ret;
}

flag MemoryInjectionAction_valueMask_Encode(const MemoryInjectionAction_valueMask* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? MemoryInjectionAction_valueMask_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, *pVal, 0, 4294967295LL);
    }

	return ret;
}

flag MemoryInjectionAction_valueMask_Decode(MemoryInjectionAction_valueMask* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 4294967295LL);
	*pErrCode = ret ? 0 : 268435459;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void MemoryInjectionAction_memoryAddress_Initialize(MemoryInjectionAction_memoryAddress* pVal)
{
    *pVal = (MemoryInjectionAction_memoryAddress) 0;
}
#endif

 
flag MemoryInjectionAction_memoryAddress_IsConstraintValid(const MemoryInjectionAction_memoryAddress* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (*pVal <= 4294967295LL);
	*pErrCode = ret ? 0 : ERR_MemoryInjectionAction_memoryAddress;

	return ret;
}

flag MemoryInjectionAction_memoryAddress_Encode(const MemoryInjectionAction_memoryAddress* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? MemoryInjectionAction_memoryAddress_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, *pVal, 0, 4294967295LL);
    }

	return ret;
}

flag MemoryInjectionAction_memoryAddress_Decode(MemoryInjectionAction_memoryAddress* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 4294967295LL);
	*pErrCode = ret ? 0 : 268435460;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void MemoryInjectionAction_injectionAddress_Initialize(MemoryInjectionAction_injectionAddress* pVal)
{
    *pVal = (MemoryInjectionAction_injectionAddress) 0;
}
#endif

 
flag MemoryInjectionAction_injectionAddress_IsConstraintValid(const MemoryInjectionAction_injectionAddress* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (*pVal <= 4294967295LL);
	*pErrCode = ret ? 0 : ERR_MemoryInjectionAction_injectionAddress;

	return ret;
}

flag MemoryInjectionAction_injectionAddress_Encode(const MemoryInjectionAction_injectionAddress* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? MemoryInjectionAction_injectionAddress_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, *pVal, 0, 4294967295LL);
    }

	return ret;
}

flag MemoryInjectionAction_injectionAddress_Decode(MemoryInjectionAction_injectionAddress* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 4294967295LL);
	*pErrCode = ret ? 0 : 268435461;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void MemoryInjectionAction_Initialize(MemoryInjectionAction* pVal)
{
    *pVal = (MemoryInjectionAction) {
    .injectionAddress = 0,
    .memoryAddress = 0,
    .valueMask = 0,
    .omitCallsNumber = 0,
    .maskOperation = 0
};
}
#endif

 
flag MemoryInjectionAction_IsConstraintValid(const MemoryInjectionAction* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = MemoryInjectionAction_injectionAddress_IsConstraintValid(&pVal->injectionAddress, pErrCode);
	if (ret) {
	    ret = MemoryInjectionAction_memoryAddress_IsConstraintValid(&pVal->memoryAddress, pErrCode);
	    if (ret) {
	        ret = MemoryInjectionAction_valueMask_IsConstraintValid(&pVal->valueMask, pErrCode);
	        if (ret) {
	            ret = MemoryInjectionAction_omitCallsNumber_IsConstraintValid(&pVal->omitCallsNumber, pErrCode);
	            if (ret) {
	                ret = MemoryInjectionAction_maskOperation_IsConstraintValid(&pVal->maskOperation, pErrCode);
	            
	            }
	        }
	    }
	}

	return ret;
}

flag MemoryInjectionAction_Encode(const MemoryInjectionAction* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? MemoryInjectionAction_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode injectionAddress */
	    ret = MemoryInjectionAction_injectionAddress_Encode(&pVal->injectionAddress, pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode memoryAddress */
	        ret = MemoryInjectionAction_memoryAddress_Encode(&pVal->memoryAddress, pBitStrm, pErrCode, FALSE);
	        if (ret) {
	            /*Encode valueMask */
	            ret = MemoryInjectionAction_valueMask_Encode(&pVal->valueMask, pBitStrm, pErrCode, FALSE);
	            if (ret) {
	                /*Encode omitCallsNumber */
	                ret = MemoryInjectionAction_omitCallsNumber_Encode(&pVal->omitCallsNumber, pBitStrm, pErrCode, FALSE);
	                if (ret) {
	                    /*Encode maskOperation */
	                    ret = MemoryInjectionAction_maskOperation_Encode(&pVal->maskOperation, pBitStrm, pErrCode, FALSE);
	                
	                }
	            }
	        }
	    }
    }

	return ret;
}

flag MemoryInjectionAction_Decode(MemoryInjectionAction* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	/*Decode injectionAddress */
	ret = MemoryInjectionAction_injectionAddress_Decode(&pVal->injectionAddress, pBitStrm, pErrCode);
	if (ret) {
	    /*Decode memoryAddress */
	    ret = MemoryInjectionAction_memoryAddress_Decode(&pVal->memoryAddress, pBitStrm, pErrCode);
	    if (ret) {
	        /*Decode valueMask */
	        ret = MemoryInjectionAction_valueMask_Decode(&pVal->valueMask, pBitStrm, pErrCode);
	        if (ret) {
	            /*Decode omitCallsNumber */
	            ret = MemoryInjectionAction_omitCallsNumber_Decode(&pVal->omitCallsNumber, pBitStrm, pErrCode);
	            if (ret) {
	                /*Decode maskOperation */
	                ret = MemoryInjectionAction_maskOperation_Decode(&pVal->maskOperation, pBitStrm, pErrCode);
	            
	            }
	        }
	    }
	}


	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void RegisterInjectionAction_maskOperation_Initialize(RegisterInjectionAction_maskOperation* pVal)
{
    *pVal = (RegisterInjectionAction_maskOperation) 0;
}
#endif

 
flag RegisterInjectionAction_maskOperation_IsConstraintValid(const RegisterInjectionAction_maskOperation* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (*pVal <= 2);
	*pErrCode = ret ? 0 : ERR_RegisterInjectionAction_maskOperation;

	return ret;
}

flag RegisterInjectionAction_maskOperation_Encode(const RegisterInjectionAction_maskOperation* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? RegisterInjectionAction_maskOperation_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, *pVal, 0, 2);
    }

	return ret;
}

flag RegisterInjectionAction_maskOperation_Decode(RegisterInjectionAction_maskOperation* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 2);
	*pErrCode = ret ? 0 : 268435462;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void RegisterInjectionAction_omitCallsNumber_Initialize(RegisterInjectionAction_omitCallsNumber* pVal)
{
    *pVal = (RegisterInjectionAction_omitCallsNumber) 0;
}
#endif

 
flag RegisterInjectionAction_omitCallsNumber_IsConstraintValid(const RegisterInjectionAction_omitCallsNumber* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (*pVal <= 4294967295LL);
	*pErrCode = ret ? 0 : ERR_RegisterInjectionAction_omitCallsNumber;

	return ret;
}

flag RegisterInjectionAction_omitCallsNumber_Encode(const RegisterInjectionAction_omitCallsNumber* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? RegisterInjectionAction_omitCallsNumber_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, *pVal, 0, 4294967295LL);
    }

	return ret;
}

flag RegisterInjectionAction_omitCallsNumber_Decode(RegisterInjectionAction_omitCallsNumber* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 4294967295LL);
	*pErrCode = ret ? 0 : 268435463;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void RegisterInjectionAction_valueMask_Initialize(RegisterInjectionAction_valueMask* pVal)
{
    *pVal = (RegisterInjectionAction_valueMask) 0;
}
#endif

 
flag RegisterInjectionAction_valueMask_IsConstraintValid(const RegisterInjectionAction_valueMask* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (*pVal <= 4294967295LL);
	*pErrCode = ret ? 0 : ERR_RegisterInjectionAction_valueMask;

	return ret;
}

flag RegisterInjectionAction_valueMask_Encode(const RegisterInjectionAction_valueMask* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? RegisterInjectionAction_valueMask_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, *pVal, 0, 4294967295LL);
    }

	return ret;
}

flag RegisterInjectionAction_valueMask_Decode(RegisterInjectionAction_valueMask* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 4294967295LL);
	*pErrCode = ret ? 0 : 268435464;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void RegisterInjectionAction_registerIndex_Initialize(RegisterInjectionAction_registerIndex* pVal)
{
    *pVal = (RegisterInjectionAction_registerIndex) 0;
}
#endif

 
flag RegisterInjectionAction_registerIndex_IsConstraintValid(const RegisterInjectionAction_registerIndex* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (*pVal <= 15);
	*pErrCode = ret ? 0 : ERR_RegisterInjectionAction_registerIndex;

	return ret;
}

flag RegisterInjectionAction_registerIndex_Encode(const RegisterInjectionAction_registerIndex* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? RegisterInjectionAction_registerIndex_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, *pVal, 0, 15);
    }

	return ret;
}

flag RegisterInjectionAction_registerIndex_Decode(RegisterInjectionAction_registerIndex* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 15);
	*pErrCode = ret ? 0 : 268435465;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void RegisterInjectionAction_injectionAddress_Initialize(RegisterInjectionAction_injectionAddress* pVal)
{
    *pVal = (RegisterInjectionAction_injectionAddress) 0;
}
#endif

 
flag RegisterInjectionAction_injectionAddress_IsConstraintValid(const RegisterInjectionAction_injectionAddress* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (*pVal <= 4294967295LL);
	*pErrCode = ret ? 0 : ERR_RegisterInjectionAction_injectionAddress;

	return ret;
}

flag RegisterInjectionAction_injectionAddress_Encode(const RegisterInjectionAction_injectionAddress* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? RegisterInjectionAction_injectionAddress_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, *pVal, 0, 4294967295LL);
    }

	return ret;
}

flag RegisterInjectionAction_injectionAddress_Decode(RegisterInjectionAction_injectionAddress* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 4294967295LL);
	*pErrCode = ret ? 0 : 268435466;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void RegisterInjectionAction_Initialize(RegisterInjectionAction* pVal)
{
    *pVal = (RegisterInjectionAction) {
    .injectionAddress = 0,
    .registerIndex = 0,
    .valueMask = 0,
    .omitCallsNumber = 0,
    .maskOperation = 0
};
}
#endif

 
flag RegisterInjectionAction_IsConstraintValid(const RegisterInjectionAction* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = RegisterInjectionAction_injectionAddress_IsConstraintValid(&pVal->injectionAddress, pErrCode);
	if (ret) {
	    ret = RegisterInjectionAction_registerIndex_IsConstraintValid(&pVal->registerIndex, pErrCode);
	    if (ret) {
	        ret = RegisterInjectionAction_valueMask_IsConstraintValid(&pVal->valueMask, pErrCode);
	        if (ret) {
	            ret = RegisterInjectionAction_omitCallsNumber_IsConstraintValid(&pVal->omitCallsNumber, pErrCode);
	            if (ret) {
	                ret = RegisterInjectionAction_maskOperation_IsConstraintValid(&pVal->maskOperation, pErrCode);
	            
	            }
	        }
	    }
	}

	return ret;
}

flag RegisterInjectionAction_Encode(const RegisterInjectionAction* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? RegisterInjectionAction_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode injectionAddress */
	    ret = RegisterInjectionAction_injectionAddress_Encode(&pVal->injectionAddress, pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode registerIndex */
	        ret = RegisterInjectionAction_registerIndex_Encode(&pVal->registerIndex, pBitStrm, pErrCode, FALSE);
	        if (ret) {
	            /*Encode valueMask */
	            ret = RegisterInjectionAction_valueMask_Encode(&pVal->valueMask, pBitStrm, pErrCode, FALSE);
	            if (ret) {
	                /*Encode omitCallsNumber */
	                ret = RegisterInjectionAction_omitCallsNumber_Encode(&pVal->omitCallsNumber, pBitStrm, pErrCode, FALSE);
	                if (ret) {
	                    /*Encode maskOperation */
	                    ret = RegisterInjectionAction_maskOperation_Encode(&pVal->maskOperation, pBitStrm, pErrCode, FALSE);
	                
	                }
	            }
	        }
	    }
    }

	return ret;
}

flag RegisterInjectionAction_Decode(RegisterInjectionAction* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	/*Decode injectionAddress */
	ret = RegisterInjectionAction_injectionAddress_Decode(&pVal->injectionAddress, pBitStrm, pErrCode);
	if (ret) {
	    /*Decode registerIndex */
	    ret = RegisterInjectionAction_registerIndex_Decode(&pVal->registerIndex, pBitStrm, pErrCode);
	    if (ret) {
	        /*Decode valueMask */
	        ret = RegisterInjectionAction_valueMask_Decode(&pVal->valueMask, pBitStrm, pErrCode);
	        if (ret) {
	            /*Decode omitCallsNumber */
	            ret = RegisterInjectionAction_omitCallsNumber_Decode(&pVal->omitCallsNumber, pBitStrm, pErrCode);
	            if (ret) {
	                /*Decode maskOperation */
	                ret = RegisterInjectionAction_maskOperation_Decode(&pVal->maskOperation, pBitStrm, pErrCode);
	            
	            }
	        }
	    }
	}


	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void InjectionConfiguration_memoryInjectionActionsNum_Initialize(InjectionConfiguration_memoryInjectionActionsNum* pVal)
{
    *pVal = (InjectionConfiguration_memoryInjectionActionsNum) 0;
}
#endif

 
flag InjectionConfiguration_memoryInjectionActionsNum_IsConstraintValid(const InjectionConfiguration_memoryInjectionActionsNum* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (*pVal <= 4294967295LL);
	*pErrCode = ret ? 0 : ERR_InjectionConfiguration_memoryInjectionActionsNum;

	return ret;
}

flag InjectionConfiguration_memoryInjectionActionsNum_Encode(const InjectionConfiguration_memoryInjectionActionsNum* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? InjectionConfiguration_memoryInjectionActionsNum_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, *pVal, 0, 4294967295LL);
    }

	return ret;
}

flag InjectionConfiguration_memoryInjectionActionsNum_Decode(InjectionConfiguration_memoryInjectionActionsNum* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 4294967295LL);
	*pErrCode = ret ? 0 : 268435467;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void InjectionConfiguration_registerInjectionActionsNum_Initialize(InjectionConfiguration_registerInjectionActionsNum* pVal)
{
    *pVal = (InjectionConfiguration_registerInjectionActionsNum) 0;
}
#endif

 
flag InjectionConfiguration_registerInjectionActionsNum_IsConstraintValid(const InjectionConfiguration_registerInjectionActionsNum* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (*pVal <= 4294967295LL);
	*pErrCode = ret ? 0 : ERR_InjectionConfiguration_registerInjectionActionsNum;

	return ret;
}

flag InjectionConfiguration_registerInjectionActionsNum_Encode(const InjectionConfiguration_registerInjectionActionsNum* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? InjectionConfiguration_registerInjectionActionsNum_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, *pVal, 0, 4294967295LL);
    }

	return ret;
}

flag InjectionConfiguration_registerInjectionActionsNum_Decode(InjectionConfiguration_registerInjectionActionsNum* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 4294967295LL);
	*pErrCode = ret ? 0 : 268435468;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void InjectionConfiguration_injectionActionsNum_Initialize(InjectionConfiguration_injectionActionsNum* pVal)
{
    *pVal = (InjectionConfiguration_injectionActionsNum) 0;
}
#endif

 
flag InjectionConfiguration_injectionActionsNum_IsConstraintValid(const InjectionConfiguration_injectionActionsNum* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (*pVal <= 4294967295LL);
	*pErrCode = ret ? 0 : ERR_InjectionConfiguration_injectionActionsNum;

	return ret;
}

flag InjectionConfiguration_injectionActionsNum_Encode(const InjectionConfiguration_injectionActionsNum* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? InjectionConfiguration_injectionActionsNum_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, *pVal, 0, 4294967295LL);
    }

	return ret;
}

flag InjectionConfiguration_injectionActionsNum_Decode(InjectionConfiguration_injectionActionsNum* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 4294967295LL);
	*pErrCode = ret ? 0 : 268435469;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void InjectionConfiguration_Initialize(InjectionConfiguration* pVal)
{
    *pVal = (InjectionConfiguration) {
    .logging = FALSE,
    .injectionActionsNum = 0,
    .registerInjectionActionsNum = 0,
    .memoryInjectionActionsNum = 0
};
}
#endif

 
flag InjectionConfiguration_IsConstraintValid(const InjectionConfiguration* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = TRUE; *pErrCode = 0;
	if (ret) {
	    ret = InjectionConfiguration_injectionActionsNum_IsConstraintValid(&pVal->injectionActionsNum, pErrCode);
	    if (ret) {
	        ret = InjectionConfiguration_registerInjectionActionsNum_IsConstraintValid(&pVal->registerInjectionActionsNum, pErrCode);
	        if (ret) {
	            ret = InjectionConfiguration_memoryInjectionActionsNum_IsConstraintValid(&pVal->memoryInjectionActionsNum, pErrCode);
	        
	        }
	    }
	}

	return ret;
}

flag InjectionConfiguration_Encode(const InjectionConfiguration* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? InjectionConfiguration_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode logging */
	    BitStream_AppendBit(pBitStrm,pVal->logging);
	    if (ret) {
	        /*Encode injectionActionsNum */
	        ret = InjectionConfiguration_injectionActionsNum_Encode(&pVal->injectionActionsNum, pBitStrm, pErrCode, FALSE);
	        if (ret) {
	            /*Encode registerInjectionActionsNum */
	            ret = InjectionConfiguration_registerInjectionActionsNum_Encode(&pVal->registerInjectionActionsNum, pBitStrm, pErrCode, FALSE);
	            if (ret) {
	                /*Encode memoryInjectionActionsNum */
	                ret = InjectionConfiguration_memoryInjectionActionsNum_Encode(&pVal->memoryInjectionActionsNum, pBitStrm, pErrCode, FALSE);
	            
	            }
	        }
	    }
    }

	return ret;
}

flag InjectionConfiguration_Decode(InjectionConfiguration* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	/*Decode logging */
	ret = BitStream_ReadBit(pBitStrm, &pVal->logging);
	*pErrCode = ret ? 0 : 268435470;
	if (ret) {
	    /*Decode injectionActionsNum */
	    ret = InjectionConfiguration_injectionActionsNum_Decode(&pVal->injectionActionsNum, pBitStrm, pErrCode);
	    if (ret) {
	        /*Decode registerInjectionActionsNum */
	        ret = InjectionConfiguration_registerInjectionActionsNum_Decode(&pVal->registerInjectionActionsNum, pBitStrm, pErrCode);
	        if (ret) {
	            /*Decode memoryInjectionActionsNum */
	            ret = InjectionConfiguration_memoryInjectionActionsNum_Decode(&pVal->memoryInjectionActionsNum, pBitStrm, pErrCode);
	        
	        }
	    }
	}


	return ret;
}

