/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>
#include "fault_injection_messages.h"

#if !defined(_MSC_VER) || _MSC_VER >= 1800
void MaskOperation_Initialize(MaskOperation* pVal)
{
    *pVal = (MaskOperation) setOperation;
}
#endif

 
flag MaskOperation_IsConstraintValid(const MaskOperation* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (((*pVal == setOperation) || (*pVal == xorOperation)) || (*pVal == orOperation));
	*pErrCode = ret ? 0 : ERR_MaskOperation;

	return ret;
}

flag MaskOperation_Encode(const MaskOperation* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? MaskOperation_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    switch(*pVal) 
	    {
	        case setOperation:   
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 0, 0, 2);
	        	break;
	        case xorOperation:   
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 1, 0, 2);
	        	break;
	        case orOperation:   
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 2, 0, 2);
	        	break;
	        default:
	    	    *pErrCode = 1073741825; //COVERAGE_IGNORE
	    	    ret = FALSE;            //COVERAGE_IGNORE
	    }
    }

	return ret;
}

flag MaskOperation_Decode(MaskOperation* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	asn1SccSint enumIndex;

	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &enumIndex, 0, 2);
	*pErrCode = ret ? 0 : 268435457;
	if (ret) {
	    switch(enumIndex) 
	    {
	        case 0: 
	            *pVal = setOperation;
	            break;
	        case 1: 
	            *pVal = xorOperation;
	            break;
	        case 2: 
	            *pVal = orOperation;
	            break;
	        default:
		        *pErrCode = 1073741826;     //COVERAGE_IGNORE
		        ret = FALSE;                //COVERAGE_IGNORE
	    }
	}

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void ExchangeStatusEnum_Initialize(ExchangeStatusEnum* pVal)
{
    *pVal = (ExchangeStatusEnum) waitingConf;
}
#endif

 
flag ExchangeStatusEnum_IsConstraintValid(const ExchangeStatusEnum* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (((*pVal == waitingConf) || (*pVal == sendingActions)) || (*pVal == actionsReceived));
	*pErrCode = ret ? 0 : ERR_ExchangeStatusEnum;

	return ret;
}

flag ExchangeStatusEnum_Encode(const ExchangeStatusEnum* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? ExchangeStatusEnum_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    switch(*pVal) 
	    {
	        case waitingConf:   
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 0, 0, 2);
	        	break;
	        case sendingActions:   
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 1, 0, 2);
	        	break;
	        case actionsReceived:   
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 2, 0, 2);
	        	break;
	        default:
	    	    *pErrCode = 1073741827; //COVERAGE_IGNORE
	    	    ret = FALSE;            //COVERAGE_IGNORE
	    }
    }

	return ret;
}

flag ExchangeStatusEnum_Decode(ExchangeStatusEnum* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	asn1SccSint enumIndex;

	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &enumIndex, 0, 2);
	*pErrCode = ret ? 0 : 268435458;
	if (ret) {
	    switch(enumIndex) 
	    {
	        case 0: 
	            *pVal = waitingConf;
	            break;
	        case 1: 
	            *pVal = sendingActions;
	            break;
	        case 2: 
	            *pVal = actionsReceived;
	            break;
	        default:
		        *pErrCode = 1073741828;     //COVERAGE_IGNORE
		        ret = FALSE;                //COVERAGE_IGNORE
	    }
	}

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void ExchangesStatus_Initialize(ExchangesStatus* pVal)
{
    *pVal = (ExchangesStatus) {
    .status = waitingConf
};
}
#endif

 
flag ExchangesStatus_IsConstraintValid(const ExchangesStatus* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = ExchangeStatusEnum_IsConstraintValid(&pVal->status, pErrCode);


	return ret;
}

flag ExchangesStatus_Encode(const ExchangesStatus* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? ExchangesStatus_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode status */
	    ret = ExchangeStatusEnum_Encode(&pVal->status, pBitStrm, pErrCode, FALSE);

    }

	return ret;
}

flag ExchangesStatus_Decode(ExchangesStatus* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	/*Decode status */
	ret = ExchangeStatusEnum_Decode(&pVal->status, pBitStrm, pErrCode);
	


	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void InjectionConfiguration_memoryInjectionActionsNum_Initialize(InjectionConfiguration_memoryInjectionActionsNum* pVal)
{
    *pVal = (InjectionConfiguration_memoryInjectionActionsNum) 0;
}
#endif

 
flag InjectionConfiguration_memoryInjectionActionsNum_IsConstraintValid(const InjectionConfiguration_memoryInjectionActionsNum* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (*pVal <= 4294967295LL);
	*pErrCode = ret ? 0 : ERR_InjectionConfiguration_memoryInjectionActionsNum;

	return ret;
}

flag InjectionConfiguration_memoryInjectionActionsNum_Encode(const InjectionConfiguration_memoryInjectionActionsNum* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? InjectionConfiguration_memoryInjectionActionsNum_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, *pVal, 0, 4294967295LL);
    }

	return ret;
}

flag InjectionConfiguration_memoryInjectionActionsNum_Decode(InjectionConfiguration_memoryInjectionActionsNum* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 4294967295LL);
	*pErrCode = ret ? 0 : 268435459;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void InjectionConfiguration_registerInjectionActionsNum_Initialize(InjectionConfiguration_registerInjectionActionsNum* pVal)
{
    *pVal = (InjectionConfiguration_registerInjectionActionsNum) 0;
}
#endif

 
flag InjectionConfiguration_registerInjectionActionsNum_IsConstraintValid(const InjectionConfiguration_registerInjectionActionsNum* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (*pVal <= 4294967295LL);
	*pErrCode = ret ? 0 : ERR_InjectionConfiguration_registerInjectionActionsNum;

	return ret;
}

flag InjectionConfiguration_registerInjectionActionsNum_Encode(const InjectionConfiguration_registerInjectionActionsNum* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? InjectionConfiguration_registerInjectionActionsNum_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, *pVal, 0, 4294967295LL);
    }

	return ret;
}

flag InjectionConfiguration_registerInjectionActionsNum_Decode(InjectionConfiguration_registerInjectionActionsNum* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 4294967295LL);
	*pErrCode = ret ? 0 : 268435460;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void InjectionConfiguration_injectionActionsNum_Initialize(InjectionConfiguration_injectionActionsNum* pVal)
{
    *pVal = (InjectionConfiguration_injectionActionsNum) 0;
}
#endif

 
flag InjectionConfiguration_injectionActionsNum_IsConstraintValid(const InjectionConfiguration_injectionActionsNum* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (*pVal <= 4294967295LL);
	*pErrCode = ret ? 0 : ERR_InjectionConfiguration_injectionActionsNum;

	return ret;
}

flag InjectionConfiguration_injectionActionsNum_Encode(const InjectionConfiguration_injectionActionsNum* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? InjectionConfiguration_injectionActionsNum_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, *pVal, 0, 4294967295LL);
    }

	return ret;
}

flag InjectionConfiguration_injectionActionsNum_Decode(InjectionConfiguration_injectionActionsNum* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 4294967295LL);
	*pErrCode = ret ? 0 : 268435461;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void InjectionConfiguration_Initialize(InjectionConfiguration* pVal)
{
    *pVal = (InjectionConfiguration) {
    .logging = FALSE,
    .injectionActionsNum = 0,
    .registerInjectionActionsNum = 0,
    .memoryInjectionActionsNum = 0
};
}
#endif

 
flag InjectionConfiguration_IsConstraintValid(const InjectionConfiguration* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = TRUE; *pErrCode = 0;
	if (ret) {
	    ret = InjectionConfiguration_injectionActionsNum_IsConstraintValid(&pVal->injectionActionsNum, pErrCode);
	    if (ret) {
	        ret = InjectionConfiguration_registerInjectionActionsNum_IsConstraintValid(&pVal->registerInjectionActionsNum, pErrCode);
	        if (ret) {
	            ret = InjectionConfiguration_memoryInjectionActionsNum_IsConstraintValid(&pVal->memoryInjectionActionsNum, pErrCode);
	        
	        }
	    }
	}

	return ret;
}

flag InjectionConfiguration_Encode(const InjectionConfiguration* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? InjectionConfiguration_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode logging */
	    BitStream_AppendBit(pBitStrm,pVal->logging);
	    if (ret) {
	        /*Encode injectionActionsNum */
	        ret = InjectionConfiguration_injectionActionsNum_Encode(&pVal->injectionActionsNum, pBitStrm, pErrCode, FALSE);
	        if (ret) {
	            /*Encode registerInjectionActionsNum */
	            ret = InjectionConfiguration_registerInjectionActionsNum_Encode(&pVal->registerInjectionActionsNum, pBitStrm, pErrCode, FALSE);
	            if (ret) {
	                /*Encode memoryInjectionActionsNum */
	                ret = InjectionConfiguration_memoryInjectionActionsNum_Encode(&pVal->memoryInjectionActionsNum, pBitStrm, pErrCode, FALSE);
	            
	            }
	        }
	    }
    }

	return ret;
}

flag InjectionConfiguration_Decode(InjectionConfiguration* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	/*Decode logging */
	ret = BitStream_ReadBit(pBitStrm, &pVal->logging);
	*pErrCode = ret ? 0 : 268435462;
	if (ret) {
	    /*Decode injectionActionsNum */
	    ret = InjectionConfiguration_injectionActionsNum_Decode(&pVal->injectionActionsNum, pBitStrm, pErrCode);
	    if (ret) {
	        /*Decode registerInjectionActionsNum */
	        ret = InjectionConfiguration_registerInjectionActionsNum_Decode(&pVal->registerInjectionActionsNum, pBitStrm, pErrCode);
	        if (ret) {
	            /*Decode memoryInjectionActionsNum */
	            ret = InjectionConfiguration_memoryInjectionActionsNum_Decode(&pVal->memoryInjectionActionsNum, pBitStrm, pErrCode);
	        
	        }
	    }
	}


	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void InjectionAction_injectionActionIndex_Initialize(InjectionAction_injectionActionIndex* pVal)
{
    *pVal = (InjectionAction_injectionActionIndex) 0;
}
#endif

 
flag InjectionAction_injectionActionIndex_IsConstraintValid(const InjectionAction_injectionActionIndex* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (*pVal <= 4294967295LL);
	*pErrCode = ret ? 0 : ERR_InjectionAction_injectionActionIndex;

	return ret;
}

flag InjectionAction_injectionActionIndex_Encode(const InjectionAction_injectionActionIndex* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? InjectionAction_injectionActionIndex_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, *pVal, 0, 4294967295LL);
    }

	return ret;
}

flag InjectionAction_injectionActionIndex_Decode(InjectionAction_injectionActionIndex* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 4294967295LL);
	*pErrCode = ret ? 0 : 268435463;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void MemoryInjectionAction_omitCallsNumber_Initialize(MemoryInjectionAction_omitCallsNumber* pVal)
{
    *pVal = (MemoryInjectionAction_omitCallsNumber) 0;
}
#endif

 
flag MemoryInjectionAction_omitCallsNumber_IsConstraintValid(const MemoryInjectionAction_omitCallsNumber* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (*pVal <= 4294967295LL);
	*pErrCode = ret ? 0 : ERR_MemoryInjectionAction_omitCallsNumber;

	return ret;
}

flag MemoryInjectionAction_omitCallsNumber_Encode(const MemoryInjectionAction_omitCallsNumber* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? MemoryInjectionAction_omitCallsNumber_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, *pVal, 0, 4294967295LL);
    }

	return ret;
}

flag MemoryInjectionAction_omitCallsNumber_Decode(MemoryInjectionAction_omitCallsNumber* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 4294967295LL);
	*pErrCode = ret ? 0 : 268435464;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void MemoryInjectionAction_valueMask_Initialize(MemoryInjectionAction_valueMask* pVal)
{
    *pVal = (MemoryInjectionAction_valueMask) 0;
}
#endif

 
flag MemoryInjectionAction_valueMask_IsConstraintValid(const MemoryInjectionAction_valueMask* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (*pVal <= 4294967295LL);
	*pErrCode = ret ? 0 : ERR_MemoryInjectionAction_valueMask;

	return ret;
}

flag MemoryInjectionAction_valueMask_Encode(const MemoryInjectionAction_valueMask* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? MemoryInjectionAction_valueMask_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, *pVal, 0, 4294967295LL);
    }

	return ret;
}

flag MemoryInjectionAction_valueMask_Decode(MemoryInjectionAction_valueMask* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 4294967295LL);
	*pErrCode = ret ? 0 : 268435465;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void MemoryInjectionAction_memoryAddress_Initialize(MemoryInjectionAction_memoryAddress* pVal)
{
    *pVal = (MemoryInjectionAction_memoryAddress) 0;
}
#endif

 
flag MemoryInjectionAction_memoryAddress_IsConstraintValid(const MemoryInjectionAction_memoryAddress* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (*pVal <= 4294967295LL);
	*pErrCode = ret ? 0 : ERR_MemoryInjectionAction_memoryAddress;

	return ret;
}

flag MemoryInjectionAction_memoryAddress_Encode(const MemoryInjectionAction_memoryAddress* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? MemoryInjectionAction_memoryAddress_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, *pVal, 0, 4294967295LL);
    }

	return ret;
}

flag MemoryInjectionAction_memoryAddress_Decode(MemoryInjectionAction_memoryAddress* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 4294967295LL);
	*pErrCode = ret ? 0 : 268435466;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void MemoryInjectionAction_injectionAddress_Initialize(MemoryInjectionAction_injectionAddress* pVal)
{
    *pVal = (MemoryInjectionAction_injectionAddress) 0;
}
#endif

 
flag MemoryInjectionAction_injectionAddress_IsConstraintValid(const MemoryInjectionAction_injectionAddress* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (*pVal <= 4294967295LL);
	*pErrCode = ret ? 0 : ERR_MemoryInjectionAction_injectionAddress;

	return ret;
}

flag MemoryInjectionAction_injectionAddress_Encode(const MemoryInjectionAction_injectionAddress* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? MemoryInjectionAction_injectionAddress_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, *pVal, 0, 4294967295LL);
    }

	return ret;
}

flag MemoryInjectionAction_injectionAddress_Decode(MemoryInjectionAction_injectionAddress* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 4294967295LL);
	*pErrCode = ret ? 0 : 268435467;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void MemoryInjectionAction_Initialize(MemoryInjectionAction* pVal)
{
    *pVal = (MemoryInjectionAction) {
    .injectionAddress = 0,
    .memoryAddress = 0,
    .valueMask = 0,
    .omitCallsNumber = 0,
    .maskOperation = setOperation
};
}
#endif

 
flag MemoryInjectionAction_IsConstraintValid(const MemoryInjectionAction* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = MemoryInjectionAction_injectionAddress_IsConstraintValid(&pVal->injectionAddress, pErrCode);
	if (ret) {
	    ret = MemoryInjectionAction_memoryAddress_IsConstraintValid(&pVal->memoryAddress, pErrCode);
	    if (ret) {
	        ret = MemoryInjectionAction_valueMask_IsConstraintValid(&pVal->valueMask, pErrCode);
	        if (ret) {
	            ret = MemoryInjectionAction_omitCallsNumber_IsConstraintValid(&pVal->omitCallsNumber, pErrCode);
	            if (ret) {
	                ret = MaskOperation_IsConstraintValid(&pVal->maskOperation, pErrCode);
	            
	            }
	        }
	    }
	}

	return ret;
}

flag MemoryInjectionAction_Encode(const MemoryInjectionAction* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? MemoryInjectionAction_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode injectionAddress */
	    ret = MemoryInjectionAction_injectionAddress_Encode(&pVal->injectionAddress, pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode memoryAddress */
	        ret = MemoryInjectionAction_memoryAddress_Encode(&pVal->memoryAddress, pBitStrm, pErrCode, FALSE);
	        if (ret) {
	            /*Encode valueMask */
	            ret = MemoryInjectionAction_valueMask_Encode(&pVal->valueMask, pBitStrm, pErrCode, FALSE);
	            if (ret) {
	                /*Encode omitCallsNumber */
	                ret = MemoryInjectionAction_omitCallsNumber_Encode(&pVal->omitCallsNumber, pBitStrm, pErrCode, FALSE);
	                if (ret) {
	                    /*Encode maskOperation */
	                    ret = MaskOperation_Encode(&pVal->maskOperation, pBitStrm, pErrCode, FALSE);
	                
	                }
	            }
	        }
	    }
    }

	return ret;
}

flag MemoryInjectionAction_Decode(MemoryInjectionAction* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	/*Decode injectionAddress */
	ret = MemoryInjectionAction_injectionAddress_Decode(&pVal->injectionAddress, pBitStrm, pErrCode);
	if (ret) {
	    /*Decode memoryAddress */
	    ret = MemoryInjectionAction_memoryAddress_Decode(&pVal->memoryAddress, pBitStrm, pErrCode);
	    if (ret) {
	        /*Decode valueMask */
	        ret = MemoryInjectionAction_valueMask_Decode(&pVal->valueMask, pBitStrm, pErrCode);
	        if (ret) {
	            /*Decode omitCallsNumber */
	            ret = MemoryInjectionAction_omitCallsNumber_Decode(&pVal->omitCallsNumber, pBitStrm, pErrCode);
	            if (ret) {
	                /*Decode maskOperation */
	                ret = MaskOperation_Decode(&pVal->maskOperation, pBitStrm, pErrCode);
	            
	            }
	        }
	    }
	}


	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void RegisterInjectionAction_omitCallsNumber_Initialize(RegisterInjectionAction_omitCallsNumber* pVal)
{
    *pVal = (RegisterInjectionAction_omitCallsNumber) 0;
}
#endif

 
flag RegisterInjectionAction_omitCallsNumber_IsConstraintValid(const RegisterInjectionAction_omitCallsNumber* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (*pVal <= 4294967295LL);
	*pErrCode = ret ? 0 : ERR_RegisterInjectionAction_omitCallsNumber;

	return ret;
}

flag RegisterInjectionAction_omitCallsNumber_Encode(const RegisterInjectionAction_omitCallsNumber* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? RegisterInjectionAction_omitCallsNumber_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, *pVal, 0, 4294967295LL);
    }

	return ret;
}

flag RegisterInjectionAction_omitCallsNumber_Decode(RegisterInjectionAction_omitCallsNumber* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 4294967295LL);
	*pErrCode = ret ? 0 : 268435468;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void RegisterInjectionAction_valueMask_Initialize(RegisterInjectionAction_valueMask* pVal)
{
    *pVal = (RegisterInjectionAction_valueMask) 0;
}
#endif

 
flag RegisterInjectionAction_valueMask_IsConstraintValid(const RegisterInjectionAction_valueMask* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (*pVal <= 4294967295LL);
	*pErrCode = ret ? 0 : ERR_RegisterInjectionAction_valueMask;

	return ret;
}

flag RegisterInjectionAction_valueMask_Encode(const RegisterInjectionAction_valueMask* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? RegisterInjectionAction_valueMask_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, *pVal, 0, 4294967295LL);
    }

	return ret;
}

flag RegisterInjectionAction_valueMask_Decode(RegisterInjectionAction_valueMask* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 4294967295LL);
	*pErrCode = ret ? 0 : 268435469;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void RegisterInjectionAction_registerIndex_Initialize(RegisterInjectionAction_registerIndex* pVal)
{
    *pVal = (RegisterInjectionAction_registerIndex) 0;
}
#endif

 
flag RegisterInjectionAction_registerIndex_IsConstraintValid(const RegisterInjectionAction_registerIndex* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (*pVal <= 15);
	*pErrCode = ret ? 0 : ERR_RegisterInjectionAction_registerIndex;

	return ret;
}

flag RegisterInjectionAction_registerIndex_Encode(const RegisterInjectionAction_registerIndex* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? RegisterInjectionAction_registerIndex_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, *pVal, 0, 15);
    }

	return ret;
}

flag RegisterInjectionAction_registerIndex_Decode(RegisterInjectionAction_registerIndex* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 15);
	*pErrCode = ret ? 0 : 268435470;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void RegisterInjectionAction_injectionAddress_Initialize(RegisterInjectionAction_injectionAddress* pVal)
{
    *pVal = (RegisterInjectionAction_injectionAddress) 0;
}
#endif

 
flag RegisterInjectionAction_injectionAddress_IsConstraintValid(const RegisterInjectionAction_injectionAddress* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (*pVal <= 4294967295LL);
	*pErrCode = ret ? 0 : ERR_RegisterInjectionAction_injectionAddress;

	return ret;
}

flag RegisterInjectionAction_injectionAddress_Encode(const RegisterInjectionAction_injectionAddress* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? RegisterInjectionAction_injectionAddress_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, *pVal, 0, 4294967295LL);
    }

	return ret;
}

flag RegisterInjectionAction_injectionAddress_Decode(RegisterInjectionAction_injectionAddress* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 4294967295LL);
	*pErrCode = ret ? 0 : 268435471;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void RegisterInjectionAction_Initialize(RegisterInjectionAction* pVal)
{
    *pVal = (RegisterInjectionAction) {
    .injectionAddress = 0,
    .registerIndex = 0,
    .valueMask = 0,
    .omitCallsNumber = 0,
    .maskOperation = setOperation
};
}
#endif

 
flag RegisterInjectionAction_IsConstraintValid(const RegisterInjectionAction* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = RegisterInjectionAction_injectionAddress_IsConstraintValid(&pVal->injectionAddress, pErrCode);
	if (ret) {
	    ret = RegisterInjectionAction_registerIndex_IsConstraintValid(&pVal->registerIndex, pErrCode);
	    if (ret) {
	        ret = RegisterInjectionAction_valueMask_IsConstraintValid(&pVal->valueMask, pErrCode);
	        if (ret) {
	            ret = RegisterInjectionAction_omitCallsNumber_IsConstraintValid(&pVal->omitCallsNumber, pErrCode);
	            if (ret) {
	                ret = MaskOperation_IsConstraintValid(&pVal->maskOperation, pErrCode);
	            
	            }
	        }
	    }
	}

	return ret;
}

flag RegisterInjectionAction_Encode(const RegisterInjectionAction* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? RegisterInjectionAction_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode injectionAddress */
	    ret = RegisterInjectionAction_injectionAddress_Encode(&pVal->injectionAddress, pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode registerIndex */
	        ret = RegisterInjectionAction_registerIndex_Encode(&pVal->registerIndex, pBitStrm, pErrCode, FALSE);
	        if (ret) {
	            /*Encode valueMask */
	            ret = RegisterInjectionAction_valueMask_Encode(&pVal->valueMask, pBitStrm, pErrCode, FALSE);
	            if (ret) {
	                /*Encode omitCallsNumber */
	                ret = RegisterInjectionAction_omitCallsNumber_Encode(&pVal->omitCallsNumber, pBitStrm, pErrCode, FALSE);
	                if (ret) {
	                    /*Encode maskOperation */
	                    ret = MaskOperation_Encode(&pVal->maskOperation, pBitStrm, pErrCode, FALSE);
	                
	                }
	            }
	        }
	    }
    }

	return ret;
}

flag RegisterInjectionAction_Decode(RegisterInjectionAction* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	/*Decode injectionAddress */
	ret = RegisterInjectionAction_injectionAddress_Decode(&pVal->injectionAddress, pBitStrm, pErrCode);
	if (ret) {
	    /*Decode registerIndex */
	    ret = RegisterInjectionAction_registerIndex_Decode(&pVal->registerIndex, pBitStrm, pErrCode);
	    if (ret) {
	        /*Decode valueMask */
	        ret = RegisterInjectionAction_valueMask_Decode(&pVal->valueMask, pBitStrm, pErrCode);
	        if (ret) {
	            /*Decode omitCallsNumber */
	            ret = RegisterInjectionAction_omitCallsNumber_Decode(&pVal->omitCallsNumber, pBitStrm, pErrCode);
	            if (ret) {
	                /*Decode maskOperation */
	                ret = MaskOperation_Decode(&pVal->maskOperation, pBitStrm, pErrCode);
	            
	            }
	        }
	    }
	}


	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void InjectionActionChoice_Initialize(InjectionActionChoice* pVal)
{
    *pVal = (InjectionActionChoice) {
    .kind = registerAction_PRESENT,
    .u = { .registerAction = {
    .injectionAddress = 0,
    .registerIndex = 0,
    .valueMask = 0,
    .omitCallsNumber = 0,
    .maskOperation = setOperation
}}
};
}
#endif

 
flag InjectionActionChoice_IsConstraintValid(const InjectionActionChoice* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	switch (pVal->kind) {
	    case registerAction_PRESENT :
	        ret = RegisterInjectionAction_IsConstraintValid(&pVal->u.registerAction, pErrCode);
	        break;
	    case memoryAction_PRESENT :
	        ret = MemoryInjectionAction_IsConstraintValid(&pVal->u.memoryAction, pErrCode);
	        break;
	    default:
		    *pErrCode = 805306369;   //COVERAGE_IGNORE
		    ret = FALSE;                    //COVERAGE_IGNORE
	}

	return ret;
}

flag InjectionActionChoice_Encode(const InjectionActionChoice* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? InjectionActionChoice_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    switch(pVal->kind) 
	    {
	    case registerAction_PRESENT:
	    	BitStream_EncodeConstraintWholeNumber(pBitStrm, 0, 0, 1);
	    	ret = RegisterInjectionAction_Encode(&pVal->u.registerAction, pBitStrm, pErrCode, FALSE);
	    	break;
	    case memoryAction_PRESENT:
	    	BitStream_EncodeConstraintWholeNumber(pBitStrm, 1, 0, 1);
	    	ret = MemoryInjectionAction_Encode(&pVal->u.memoryAction, pBitStrm, pErrCode, FALSE);
	    	break;
	    default:
	        *pErrCode = 805306370;         //COVERAGE_IGNORE
	        ret = FALSE;                    //COVERAGE_IGNORE
	    }
    }

	return ret;
}

flag InjectionActionChoice_Decode(InjectionActionChoice* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	asn1SccSint nChoiceIndex;

	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &nChoiceIndex, 0, 1);
	*pErrCode = ret ? 0 : 268435472;
	if (ret) {
	    switch(nChoiceIndex) 
	    {
	    case 0:
	    	pVal->kind = registerAction_PRESENT;
	    	ret = RegisterInjectionAction_Decode(&pVal->u.registerAction, pBitStrm, pErrCode);
	    	break;
	    case 1:
	    	pVal->kind = memoryAction_PRESENT;
	    	ret = MemoryInjectionAction_Decode(&pVal->u.memoryAction, pBitStrm, pErrCode);
	    	break;
	    default:
	        *pErrCode = 805306371;     //COVERAGE_IGNORE
	        ret = FALSE;                //COVERAGE_IGNORE
	    }
	}

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void InjectionAction_Initialize(InjectionAction* pVal)
{
    *pVal = (InjectionAction) {
    .injectionAction = {
        .kind = registerAction_PRESENT,
        .u = { .registerAction = {
        .injectionAddress = 0,
        .registerIndex = 0,
        .valueMask = 0,
        .omitCallsNumber = 0,
        .maskOperation = setOperation
    }}
    },
    .injectionActionIndex = 0
};
}
#endif

 
flag InjectionAction_IsConstraintValid(const InjectionAction* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = InjectionActionChoice_IsConstraintValid(&pVal->injectionAction, pErrCode);
	if (ret) {
	    ret = InjectionAction_injectionActionIndex_IsConstraintValid(&pVal->injectionActionIndex, pErrCode);
	
	}

	return ret;
}

flag InjectionAction_Encode(const InjectionAction* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? InjectionAction_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode injectionAction */
	    ret = InjectionActionChoice_Encode(&pVal->injectionAction, pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode injectionActionIndex */
	        ret = InjectionAction_injectionActionIndex_Encode(&pVal->injectionActionIndex, pBitStrm, pErrCode, FALSE);
	    
	    }
    }

	return ret;
}

flag InjectionAction_Decode(InjectionAction* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	/*Decode injectionAction */
	ret = InjectionActionChoice_Decode(&pVal->injectionAction, pBitStrm, pErrCode);
	if (ret) {
	    /*Decode injectionActionIndex */
	    ret = InjectionAction_injectionActionIndex_Decode(&pVal->injectionActionIndex, pBitStrm, pErrCode);
	
	}


	return ret;
}

